apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    creation_method: manual
    env: prod
spec: 
  containers:
    - image: dgunjetti/kubia
      name: kubia
      ports:
        - containersPort: 8080
          protocol: tcp
